<a href="https://colab.research.google.com/github/1129Chengyuan/PyTorchLearning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   They are similar to Numpy Arrays, but they work better on GPUs
*   Default type: float32
*   More suitable for deep learning than a numpy array.





In [4]:
import torch
import numpy as np

# Lists

In [2]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


# Numpy arrays

In [5]:
np1 = np.random.rand(3,4)
print(np1)

[[0.15437557 0.01880519 0.27643662 0.92680527]
 [0.46970535 0.53728093 0.88860987 0.3798621 ]
 [0.93415966 0.816136   0.914979   0.88011113]]


In [6]:
print(np1.dtype)

float64


# Tensor

In [7]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)

tensor([[ 2.8188,  1.0085,  1.0106,  1.1325],
        [ 1.3289, -0.4898, -1.4305,  1.0338],
        [-0.4649,  0.8415, -0.2081,  1.1163]])


In [9]:
tensor_3d = torch.zeros(3,4,5)
print(tensor_3d)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [10]:
##Creating a tensor out of a numpy array!
my_tensor = torch.tensor(np1)
print(my_tensor) #this is a float64 type because the type for numpy is float64

tensor([[0.1544, 0.0188, 0.2764, 0.9268],
        [0.4697, 0.5373, 0.8886, 0.3799],
        [0.9342, 0.8161, 0.9150, 0.8801]], dtype=torch.float64)
