<a href="https://colab.research.google.com/github/1129Chengyuan/PyTorchLearning/blob/main/TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
# Reshape and View
my_torch = my_torch.reshape(2,5) #If the input size is wrong it will throw an error
print(my_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [5]:
# Reshape if we don't know the number of items
my_torch2 = torch.arange(10)
print(my_torch2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [8]:
my_torch2 = my_torch2.reshape(2, -1) #use -1 to denote an unknown value!
# Note: Even if you use -1, a rectangular shape has to be preserved
print(my_torch2)
my_torch2 = my_torch2.reshape(-1, 5)
print(my_torch2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [10]:
my_torch3 = torch.arange(10)
print(my_torch3)
my_torch4 = my_torch3.view(2,5)
print(my_torch4)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


# So what's the difference?
While it seems like both *view* and *reshape* return a manipulated version of the object, how they handle tensors depends on whether or not it is contiguous...

A contiguous tensor is a tensor whose values are stored in a single, uninterrupted piece of memory. On the other hand, a non-contiguous tensor may have gaps in its memory layout.

* If applied to a contiguous tensor, both *view* and *reshape* produces a new "view" of the given tensor's memory. In other words, they interpret the contiguous tensor as an alternate layout - a piece of memory that stores 16 values, for example, could be viewed as a 4x4 element 2D tensor instead.

* If applied to a non-contiguous tensor, the *reshape* method produces a duplicate of the piece of memory, returning a tensor whose memory is not shared with the given tensor. On the other hand, the *view* method throws a *RunTime Error*.

It is important to keep in mind that view objects created reference the data in the original, so any changes would be reflected in the *view* and *reshape* objects!

In [1]:
from torch import arange

contiguous = arange(16).view(4, 4)             # Create contiguous 4×4 tensor
noncontiguous = arange(20).view(4, 5)[:, :4]   # Create non-contiguous 4×4 tensor

contiguous_r = contiguous.reshape(16)          # OK: produces a 1-d view
assert contiguous_r.data_ptr() == contiguous.data_ptr()  # Same memory used

contiguous_v = contiguous.view(16)             # OK: produces a 1-d view
assert contiguous_v.data_ptr() == contiguous.data_ptr()  # Same memory used

noncontiguous_r = noncontiguous.reshape(16)    # OK: produces a new 1-d array
assert noncontiguous_r.data_ptr() != noncontiguous.data_ptr()  # New memory used

noncontiguous_v = noncontiguous.view(16)       # ERROR: cannot produce view

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [1]:
# Changes will be reflected!
my_torch5 = torch.arange(10)
print(my_torch5)
my_torch6 = my_torch5.reshape(2,5)
print(my_torch6)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [3]:
my_torch5[1] = 4141
print(my_torch5)
print(my_torch6)

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


# Slices

In [4]:
my_torch7 = torch.arange(10)
print(my_torch7)
# Grabbing a specific item
print(my_torch7[7]) # Output: tensor(7)
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
print(my_torch8)
print(my_torch8[:,1]) # Output: tensor([1, 3, 5, 7, 9])
print(my_torch8[:,1:])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(7)
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])
